language: python
python:
  - "2.7"
  - "3.4"
  - "3.7"
install:
  - pip install -e .
  - pip install pytest pytest-cov codacy-coverage
script: py.test -v --color=yes --cov-report xml --cov=canopen test/
after_script: python-codacy-coverage
