language: python
python:
  - "2.7"
  - "3.3"
  - "3.6"
install:
  - pip install -e .
  - pip install pytest pytest-cov codacy-coverage
script: pytest -v --cov-report xml --cov=canopen test/
after_script: python-codacy-coverage -r coverage.xml
