language: python
python:
  - "2.7"
  - "3.3"
  - "3.6"
install: pip install . nose coverage codacy-coverage
script: nosetests --with-coverage --cover-package=canopen --cover-xml
after_script: python-codacy-coverage -r coverage.xml
